# Generated by Django 3.1.5 on 2021-01-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Sarlavha')),
                ('anons', models.CharField(max_length=250, verbose_name='anons')),
                ('full_text', models.TextField(verbose_name='Maqola')),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
